name: Test & Deploy
on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo 'hello...'
  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo and checkout main
        uses: actions/checkout@v4
      - name: install our dependencies
        run: npm ci
      - name: run tests
        run: npm run test-utils
  test-app:
    runs-on: ubuntu-latest
    needs: test-utils
    steps:
      - name: clone repo and checkout main
        uses: actions/checkout@v4
      - name: install our dependencies
        run: npm ci
      - name: setup of psql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: test_user
          postgresql password: password
      - name: run tests
        run: PGDATABASE=test_db PGUSER=test_user PGPASSWORD=password npm test app
  test-with-live-db:
    runs-on: ubuntu-latest
    needs: test-app
    steps:
      - name: clone repo and checkout main
        uses: actions/checkout@v4
      - name: install our dependencies
        run: npm ci
      - name: run tests
        run: NODE_ENV=production DATABASE_URL=${{ secrets.DATABASE_URL }} npm run test app
